import { Edit3, Plus, Search, Trash2, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { toast } from 'react-toastify';
import { api, getSession } from '../../../services/api.js';
import { can } from '../../../utils/permissions.js';

const empty = { leadId: '', personId: '', name: '', role: '', number: '', email: '' };
export default function CustomersWorkspace({ leads, setLeads, token }) {
  const user = getSession()?.user;
  const canCreate = can(user, 'customers.create');
  const canEdit = can(user, 'customers.edit');
  const canDelete = can(user, 'customers.delete');
  const [search, setSearch] = useState(() => new URLSearchParams(window.location.search).get('lookup') || ''); const [dialog, setDialog] = useState(null); const [form, setForm] = useState(empty); const [saving, setSaving] = useState(false);
  const customers = useMemo(() => leads.flatMap((lead) => (lead.companyPersons || []).map((person, index) => ({ ...person, _id: person._id || `${lead._id}-${index}`, leadId: lead._id, company: lead.company || 'Unnamed company', leadCreatedAt: lead.createdAt }))).filter((person) => `${person.name} ${person.role} ${person.number} ${person.email} ${person.company}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => {
    const aId = /^[a-f\d]{24}$/i.test(String(a._id)) ? String(a._id) : '';
    const bId = /^[a-f\d]{24}$/i.test(String(b._id)) ? String(b._id) : '';
    if (aId && bId) return bId.localeCompare(aId);
    return new Date(b.leadCreatedAt || 0) - new Date(a.leadCreatedAt || 0);
  }), [leads, search]);
  function openCreate() { setForm(empty); setDialog('create'); }
  function openEdit(customer) { setForm({ leadId: customer.leadId, personId: customer._id, name: customer.name || '', role: customer.role || customer.designation || '', number: customer.number || customer.contactNumber || '', email: customer.email || '' }); setDialog('edit'); }
  async function save(event) { event.preventDefault(); const lead = leads.find((item) => String(item._id) === String(form.leadId)); if (!lead) return toast.error('Select a company lead.'); setSaving(true); try { const details = { name: form.name.trim(), role: form.role.trim(), number: form.number.trim(), email: form.email.trim() }; const result = dialog === 'edit' ? await api.updateCustomer(token, lead._id, form.personId, details) : await api.createCustomer(token, lead._id, details); setLeads((current) => current.map((item) => item._id === lead._id ? result.lead : item)); setDialog(null); toast.success(dialog === 'edit' ? 'Customer updated.' : 'Customer added.'); } catch (error) { toast.error(error.message); } finally { setSaving(false); } }
  async function remove(customer) { if (!window.confirm(`Delete ${customer.name || 'this customer'}?`)) return; try { const result = await api.deleteCustomer(token, customer.leadId, customer._id); setLeads((current) => current.map((lead) => lead._id === customer.leadId ? result.lead : lead)); toast.success('Customer deleted.'); } catch (error) { toast.error(error.message); } }
  return <div className="crm-content-inner customers-page"><div className="section-heading"><div><h1>Customers</h1><p>Manage people connected to your company leads.</p></div>{canCreate && <button className="primary-action" type="button" onClick={openCreate}><Plus size={17} />Add customer</button>}</div><div className="product-toolbar"><label className="user-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search customer or company" /></label></div><div className="product-table-wrap"><table className="product-table"><thead><tr><th>Name</th><th>Company</th><th>Role</th><th>Number</th><th>Email</th><th>Actions</th></tr></thead><tbody>{customers.length ? customers.map((customer) => <tr key={customer._id} data-record-id={customer._id}><td><strong>{customer.name || 'Unnamed customer'}</strong></td><td>{customer.company}</td><td>{customer.role || '—'}</td><td>{customer.number || '—'}</td><td>{customer.email || '—'}</td><td><div className="table-actions">{canEdit && <button className="icon-action edit" type="button" title="Edit customer" onClick={() => openEdit(customer)}><Edit3 size={16} /></button>}{canDelete && <button className="icon-action delete" type="button" title="Delete customer" onClick={() => remove(customer)}><Trash2 size={16} /></button>}</div></td></tr>) : <tr><td className="empty-table" colSpan="6">No customers found.</td></tr>}</tbody></table></div>{dialog && <div className="modal-backdrop" role="presentation"><form className="user-modal" onSubmit={save}><div className="modal-heading"><div><span className="dashboard-kicker">Customer directory</span><h2>{dialog === 'edit' ? 'Edit customer' : 'Add customer'}</h2></div><button className="modal-close" type="button" onClick={() => setDialog(null)} aria-label="Close"><X size={18} /></button></div><div className="modal-fields"><label>Company lead *<select required value={form.leadId} disabled={dialog === 'edit'} onChange={(event) => setForm({ ...form, leadId: event.target.value })}><option value="">Select company</option>{leads.map((lead) => <option key={lead._id} value={lead._id}>{lead.company || 'Unnamed company'}</option>)}</select></label><label>Name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Role<input value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} /></label><label>Number<input value={form.number} onChange={(event) => setForm({ ...form, number: event.target.value })} /></label><label>Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label></div><div className="modal-footer"><button className="secondary-action" type="button" onClick={() => setDialog(null)}>Cancel</button><button className="primary-action" disabled={saving} type="submit">{saving ? 'Saving…' : 'Save customer'}</button></div></form></div>}</div>;
}
